#!/usr/bin/env python3
"""Translate all [Arabic translation needed] placeholders in intentional-parent.ts
Uses a two-pass approach:
1. Match English text on same line to translate labels, titles, questions, etc.
2. Handle multi-line/standalone Ar fields by looking at the corresponding En field above.
"""
import re

filepath = 'src/data/programs/intentional-parent.ts'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

count_before = content.count('[Arabic translation needed]')
print(f"Placeholders before: {count_before}")

# ============================================================
# PASS 1: Direct string replacements for items where the
# English text and [Arabic translation needed] are on the SAME line
# ============================================================

# This massive dictionary maps English strings to Arabic translations.
# The script searches each line containing [Arabic translation needed]
# for any of these English strings, and if found, replaces the placeholder.

t = {
    # SHARED / REUSABLE across modules
    "Not at all": "لا على الإطلاق",
    "Very much so": "بالتأكيد",
    "Very Difficult": "صعب جداً",
    "Natural for Me": "طبيعي بالنسبة لي",
    "Strongly Disagree": "أعارض بشدة",
    "Strongly Agree": "أوافق بشدة",
    "Never": "أبداً",
    "Weekly": "أسبوعياً",
    "Rarely": "نادراً",
    "Daily": "يومياً",
    "transition": "انتقال",
    "drives": "يدفع",
    "fuels": "يغذي",
    "Mostly Punitive": "عقابي في الغالب",
    "Mostly Teaching": "تعليمي في الغالب",
    "I usually rescue": "عادة أنقذ",
    "I validate and support": "أؤكد وأدعم",
    "Unaware": "غير واعٍ",
    "Highly Intentional": "واعٍ بشكل كبير",
    "Absolutely": "بالتأكيد",
    "Always": "دائماً",
    "next time, slightly easier": "المرة القادمة أسهل قليلاً",
    "next time, easier to repair": "المرة القادمة أسهل للإصلاح",
    "reflect": "تأمل",
    "build": "ابنِ",
    "next generation inherits": "الجيل القادم يرث",
    "Routine (functional task)": "روتين (مهمة وظيفية)",
    "Ritual (emotionally meaningful)": "طقس (ذو معنى عاطفي)",
    "Active Engagement": "تفاعل نشط",
    "Passive Consumption": "استهلاك سلبي",

    # MODULE 1.4: Building Daily Rituals
    "What is the key difference between a routine and a ritual?": "ما الفرق الرئيسي بين الروتين والطقس؟",
    "Routines are for mornings and rituals are for bedtime": "الروتين للصباح والطقوس لوقت النوم",
    "Routines are functional while rituals carry emotional meaning": "الروتين وظيفي بينما الطقوس تحمل معنى عاطفياً",
    "Rituals take more time than routines": "الطقوس تستغرق وقتاً أكثر من الروتين",
    "There is no real difference between the two": "لا يوجد فرق حقيقي بين الاثنين",
    "Why are transition moments especially powerful for rituals?": "لماذا تكون لحظات الانتقال قوية بشكل خاص للطقوس؟",
    "Because children are most obedient during transitions": "لأن الأطفال يكونون أكثر طاعة أثناء الانتقالات",
    "Because transitions are emotional pivot points involving separation and reunion": "لأن الانتقالات هي نقاط محورية عاطفية تتضمن الانفصال والالتقاء",
    "Because parents have the most free time during transitions": "لأن الوالدين لديهم أكثر وقت فراغ أثناء الانتقالات",
    "Because transitions are the only time children pay attention": "لأن الانتقالات هي الوقت الوحيد الذي ينتبه فيه الأطفال",
    "How can cultural heritage be incorporated into family rituals?": "كيف يمكن دمج التراث الثقافي في طقوس الأسرة؟",
    "By replacing all modern practices with traditional ones": "باستبدال جميع الممارسات الحديثة بالتقليدية",
    "Cultural traditions are not relevant to daily rituals": "التقاليد الثقافية ليست ذات صلة بالطقوس اليومية",
    "By weaving cultural greetings, prayers, or storytelling into daily rhythms": "بنسج التحيات الثقافية والأدعية أو رواية القصص في الإيقاعات اليومية",
    "By only practicing cultural traditions on holidays": "بممارسة التقاليد الثقافية في المناسبات فقط",
    "What should you do when rituals are missed due to a busy day?": "ماذا يجب أن تفعل عندما تُفوَّت الطقوس بسبب يوم مزدحم؟",
    "Abandon the ritual entirely since consistency was broken": "التخلي عن الطقس تماماً لأن الاستمرارية انكسرت",
    "Feel guilty and make up for it with a bigger gesture": "الشعور بالذنب والتعويض بإيماءة أكبر",
    "Be gentle with yourself and return to the ritual when you can": "كن لطيفاً مع نفسك وعد إلى الطقس عندما تستطيع",
    "Create a new ritual to replace the old one": "ابتكر طقساً جديداً ليحل محل القديم",
    "We are a blended family. How do we create rituals that feel inclusive?": "نحن عائلة مختلطة. كيف نبتكر طقوساً تشعر الجميع بالشمول؟",
    'My child is resistant to new rituals and says they are "silly." What should I do?': 'طفلي يقاوم الطقوس الجديدة ويقول إنها "سخيفة". ماذا أفعل؟',
    "Distinguish between routines (functional) and rituals (emotionally meaningful)": "ميّز بين الروتين (الوظيفي) والطقوس (ذات المعنى العاطفي)",
    "Design at least one new family ritual for a transition moment": "صمّم طقساً عائلياً جديداً واحداً على الأقل للحظة انتقالية",
    "Incorporate cultural heritage elements into daily family rituals": "أدمج عناصر التراث الثقافي في طقوس الأسرة اليومية",
    "A Review of 50 Years of Research on Naturally Occurring Family Routines and Rituals": "مراجعة خمسين عاماً من الأبحاث حول الروتين والطقوس العائلية الطبيعية",
    "Family Routines and Rituals: A Context for Development in the Lives of Young Children": "الروتين والطقوس العائلية: سياق للنمو في حياة الأطفال الصغار",
    "The Rushed Morning": "الصباح المستعجل",
    "You realize mornings have become purely transactional. What is your first step?": "تدرك أن الصباحات أصبحت معاملات بحتة. ما هي خطوتك الأولى؟",
    "Rituals vs. Routines": "الطقوس مقابل الروتين",
    "Brushing teeth before bed": "تنظيف الأسنان قبل النوم",
    "A special goodnight phrase said every night": "عبارة تصبح على خير خاصة تُقال كل ليلة",
    "Packing school lunches": "تحضير وجبات الغداء المدرسية",
    "Sharing three grateful things at dinner": "مشاركة ثلاثة أشياء ممتنين لها على العشاء",
    "Family Ritual Strength": "قوة الطقوس العائلية",
    "Ritual Opportunity": "فرصة للطقوس",
    "Growing Rituals": "طقوس نامية",
    "Ritual-Rich Family": "عائلة غنية بالطقوس",
    "The Daily Ritual Cycle": "دورة الطقوس اليومية",
    "Morning Greeting": "تحية الصباح",
    "Goodbye Ritual": "طقس الوداع",
    "Reunion Ritual": "طقس الالتقاء",
    "Bedtime Ritual": "طقس النوم",
    "Start the day with a warm connection ritual": "ابدأ اليوم بطقس تواصل دافئ",
    "Mark the separation with a meaningful moment": "ميّز الانفصال بلحظة ذات معنى",
    "Reconnect when you come back together": "أعد التواصل عندما تجتمعون مجدداً",
    "Close the day with security and love": "أغلق اليوم بالأمان والحب",
    "Categorize each activity as a Routine or a Ritual.": "صنّف كل نشاط كروتين أو طقس.",

    # MODULE 1.5: Emotional Co-Regulation
    "What is co-regulation?": "ما هو التنظيم المشترك؟",
    "Teaching children to manage emotions on their own": "تعليم الأطفال إدارة مشاعرهم بمفردهم",
    "Using your calm presence to help a child's nervous system settle": "استخدام حضورك الهادئ لمساعدة الجهاز العصبي للطفل على الاستقرار",
    "Telling a child to calm down when they are upset": "إخبار الطفل بالهدوء عندما يكون منزعجاً",
    "Ignoring a child's emotions until they stop on their own": "تجاهل مشاعر الطفل حتى تتوقف من تلقاء نفسها",
    'Why does telling a distressed child to "calm down" rarely work?': 'لماذا نادراً ما ينجح إخبار الطفل المنزعج بأن "يهدأ"؟',
    "Because children are naturally defiant": "لأن الأطفال متمردون بطبيعتهم",
    "Because the logical part of their brain has gone offline during strong emotions": "لأن الجزء المنطقي من دماغهم يتوقف عن العمل أثناء المشاعر القوية",
    "Because they do not understand the words": "لأنهم لا يفهمون الكلمات",
    "Because they want attention from their parent": "لأنهم يريدون اهتماماً من والديهم",
    'What does "name it to tame it" mean?': 'ما معنى "سمِّه لتروِّضه"؟',
    "Giving a child a nickname to make them feel better": "إعطاء الطفل لقباً ليشعر بتحسن",
    "Writing the emotion on a piece of paper": "كتابة المشاعر على ورقة",
    "Labeling the emotion helps the brain organize and process the experience": "تسمية المشاعر تساعد الدماغ على تنظيم التجربة ومعالجتها",
    "Telling the child to name three things they see in the room": "إخبار الطفل بتسمية ثلاثة أشياء يراها في الغرفة",
    "Why is parental self-care essential for co-regulation?": "لماذا تعتبر العناية الذاتية للوالدين ضرورية للتنظيم المشترك؟",
    "Because parents deserve time away from their children": "لأن الوالدين يستحقون وقتاً بعيداً عن أطفالهم",
    "Because you cannot anchor a child if your own nervous system is dysregulated": "لأنك لا تستطيع أن تكون مرساة لطفلك إذا كان جهازك العصبي مضطرباً",
    "Because children learn to care for themselves by watching parents relax": "لأن الأطفال يتعلمون الاعتناء بأنفسهم بمراقبة استرخاء الوالدين",
    "Self-care is optional and unrelated to co-regulation": "العناية الذاتية اختيارية ولا علاقة لها بالتنظيم المشترك",
    "What if I lose my temper during my child's meltdown? Have I failed at co-regulation?": "ماذا لو فقدت أعصابي أثناء انهيار طفلي؟ هل فشلت في التنظيم المشترك؟",
    "My child resists physical touch when they are upset. How can I co-regulate without touch?": "طفلي يرفض اللمس الجسدي عندما يكون منزعجاً. كيف يمكنني التنظيم المشترك بدون لمس؟",
    "At what age can children start to self-regulate without co-regulation?": "في أي عمر يمكن للأطفال البدء بالتنظيم الذاتي بدون التنظيم المشترك؟",
    "Explain the neuroscience behind why children cannot self-regulate during emotional flooding": "وضّح العلم العصبي وراء عدم قدرة الأطفال على التنظيم الذاتي أثناء الغمر العاطفي",
    "Practice co-regulation techniques including calm voice, gentle touch, and slow breathing": "مارس تقنيات التنظيم المشترك بما في ذلك الصوت الهادئ واللمس اللطيف والتنفس البطيء",
    "Identify personal triggers that dysregulate your own nervous system": "حدّد المحفزات الشخصية التي تُربك جهازك العصبي",
    "Distinguish between co-regulation and emotional absorption": "ميّز بين التنظيم المشترك والامتصاص العاطفي",
    "The Whole-Brain Child: 12 Revolutionary Strategies to Nurture Your Child's Developing Mind": "طفل الدماغ الكامل: ١٢ استراتيجية ثورية لتنمية عقل طفلك النامي",
    "The Polyvagal Theory: Neurophysiological Foundations of Emotions, Attachment, Communication, and Self-Regulation": "نظرية البوليفاغال: الأسس الفسيولوجية العصبية للمشاعر والتعلق والتواصل والتنظيم الذاتي",
    "Developing Through Relationships: Origins of Communication, Self, and Culture": "النمو من خلال العلاقات: أصول التواصل والذات والثقافة",
    "The Broken Cracker Crisis": "أزمة البسكويت المكسور",
    "Co-Regulation Tools": "أدوات التنظيم المشترك",
    "Match each co-regulation tool with how it works.": "طابق كل أداة تنظيم مشترك مع كيفية عملها.",
    "Calm, slow voice": "صوت هادئ وبطيء",
    "Activates the child's parasympathetic nervous system": "ينشط الجهاز العصبي اللاودي للطفل",
    "Gentle touch on back": "لمسة لطيفة على الظهر",
    "Can slow heart rate and communicate physical safety": "يمكن أن يبطئ نبض القلب ويوصل شعوراً بالأمان الجسدي",
    "Physical proximity": "القرب الجسدي",
    "Communicates safety without requiring words": "يوصل شعوراً بالأمان دون الحاجة إلى كلمات",
    "Naming the emotion": "تسمية المشاعر",
    "Helps the brain move from flooding to processing": "يساعد الدماغ على الانتقال من الغمر إلى المعالجة",
    "Deep breathing near the child": "التنفس العميق بالقرب من الطفل",
    "Child unconsciously mirrors your regulated breathing pattern": "الطفل يعكس لا شعورياً نمط تنفسك المنظم",
    "Self-Regulation Readiness": "جاهزية التنظيم الذاتي",
    "Easily Activated": "سهل الاستثارة",
    "Building Steadiness": "بناء الثبات",
    "Steady Anchor": "مرساة ثابتة",
    "The Co-Regulation Process": "عملية التنظيم المشترك",
    "Child Becomes Dysregulated": "الطفل يصبح مضطرباً",
    "Big emotion overwhelms the child's immature nervous system": "مشاعر كبيرة تغمر الجهاز العصبي غير الناضج للطفل",
    "Parent Self-Regulates": "الوالد ينظم نفسه",
    "Take breaths, ground yourself, pause before responding": "خذ أنفاساً عميقة، ثبّت نفسك، توقف قبل الاستجابة",
    "Co-Regulation": "التنظيم المشترك",
    "Calm voice, proximity, touch, naming the emotion": "صوت هادئ، قرب، لمس، تسمية المشاعر",
    "Child's System Settles": "جهاز الطفل يهدأ",
    "Mirroring your calm, the child's nervous system begins to regulate": "بعكس هدوئك، يبدأ الجهاز العصبي للطفل بالتنظيم",
    "Child Internalizes Skills": "الطفل يستوعب المهارات",
    "Over time, your calm voice becomes their inner voice": "مع الوقت يصبح صوتك الهادئ صوتهم الداخلي",

    # MODULE 2.1: Discipline Without Damage
    'What does the word "discipline" originally mean?': 'ما المعنى الأصلي لكلمة "التأديب"؟',
    "To punish": "العقاب",
    "To control": "السيطرة",
    "To teach": "التعليم",
    "To restrict": "التقييد",
    "Why is stating rules in positive terms more effective?": "لماذا يكون تقديم القواعد بصيغة إيجابية أكثر فعالية؟",
    "Because negative words confuse children": "لأن الكلمات السلبية تُربك الأطفال",
    "Because it gives children a clear picture of what to do": "لأنها تعطي الأطفال صورة واضحة عما يجب فعله",
    'Because children cannot understand the word "no"': 'لأن الأطفال لا يستطيعون فهم كلمة "لا"',
    "Because positive words are always kinder": "لأن الكلمات الإيجابية دائماً ألطف",
    "What is the difference between natural and logical consequences?": "ما الفرق بين العواقب الطبيعية والمنطقية؟",
    "Natural consequences are harsher than logical ones": "العواقب الطبيعية أقسى من المنطقية",
    "Natural consequences happen on their own; logical ones are parent-created but related to the behavior": "العواقب الطبيعية تحدث من تلقاء نفسها؛ والمنطقية يضعها الوالدان لكنها مرتبطة بالسلوك",
    "Logical consequences are punishments and natural consequences are rewards": "العواقب المنطقية عقوبات والطبيعية مكافآت",
    "There is no meaningful difference between them": "لا يوجد فرق ذو معنى بينهما",
    "Why is repair important after a disciplinary moment?": "لماذا الإصلاح مهم بعد لحظة تأديبية؟",
    "It teaches children that mistakes break the relationship permanently": "يعلّم الأطفال أن الأخطاء تكسر العلاقة بشكل دائم",
    "It shows children that the parent was wrong": "يُظهر للأطفال أن الوالد كان مخطئاً",
    "It teaches that mistakes do not break the relationship and every day is a fresh start": "يعلّم أن الأخطاء لا تكسر العلاقة وأن كل يوم بداية جديدة",
    "It is only necessary after physical discipline": "ضروري فقط بعد العقاب الجسدي",
    "Is it ever okay to raise my voice with my child?": "هل من المقبول أبداً أن أرفع صوتي مع طفلي؟",
    "How do I handle discipline when grandparents use different methods?": "كيف أتعامل مع التأديب عندما يستخدم الأجداد أساليب مختلفة؟",
    "Explain the four pillars of healthy discipline: clarity, calm enforcement, consequences, and repair": "وضّح الركائز الأربع للتأديب الصحي: الوضوح والتطبيق الهادئ والعواقب والإصلاح",
    "Reframe discipline from punishment to teaching in daily interactions": "أعد صياغة التأديب من العقاب إلى التعليم في التفاعلات اليومية",
    "Apply natural and logical consequences appropriately based on the child's age": "طبّق العواقب الطبيعية والمنطقية بشكل مناسب بناءً على عمر الطفل",
    "Spanking and Child Outcomes: Old Controversies and New Meta-Analyses": "الضرب ونتائج الأطفال: جدالات قديمة وتحليلات تلوية جديدة",
    "No-Drama Discipline: The Whole-Brain Way to Calm the Chaos and Nurture Your Child's Developing Mind": "التأديب بلا دراما: طريقة الدماغ الكامل لتهدئة الفوضى وتنمية عقل طفلك النامي",
    "The Drawing on the Wall": "الرسم على الجدار",
    "Four Pillars of Healthy Discipline": "الركائز الأربع للتأديب الصحي",
    "Match each pillar with its description.": "طابق كل ركيزة مع وصفها.",
    "Clarity": "الوضوح",
    "Stating rules in positive terms so children know what to do": "تقديم القواعد بصيغة إيجابية ليعرف الأطفال ما يجب فعله",
    "Calm Enforcement": "التطبيق الهادئ",
    "Responding with firm composure rather than anger": "الاستجابة بحزم هادئ بدلاً من الغضب",
    "Natural Consequences": "العواقب الطبيعية",
    "Allowing real-world outcomes to teach the lesson": "السماح لنتائج العالم الحقيقي بتعليم الدرس",
    "Repair": "الإصلاح",
    "Reconnecting after the disciplinary moment to restore trust": "إعادة التواصل بعد اللحظة التأديبية لاستعادة الثقة",
    "Discipline Approach Check": "فحص نهج التأديب",
    "When my child misbehaves, I focus on teaching rather than punishing.": "عندما يسيء طفلي التصرف أركز على التعليم بدلاً من العقاب.",
    "Punishment-Focused": "يركز على العقاب",
    "In Transition": "في مرحلة انتقالية",
    "Teaching-Oriented": "موجه نحو التعليم",
    "The Discipline Decision Flow": "مسار قرار التأديب",
    "Child Breaks a Rule": "الطفل يخالف قاعدة",
    "A boundary has been crossed": "تم تجاوز حد",
    "Parent Pauses": "الوالد يتوقف",
    "Take a breath before reacting": "خذ نفساً قبل الاستجابة",
    "State Rule Calmly": "اذكر القاعدة بهدوء",
    "Use positive terms: what TO do": "استخدم صيغة إيجابية: ماذا يجب أن تفعل",
    "Apply Consequence": "طبّق العاقبة",
    "Natural or logical, related to behavior": "طبيعية أو منطقية مرتبطة بالسلوك",
    "Repair & Reconnect": "أصلح وأعد التواصل",
    "Come back together with love": "عودوا معاً بحب",

    # MODULE 2.2: Screen Time
    "What matters more than the total number of minutes of screen time?": "ما الذي يهم أكثر من إجمالي عدد دقائق وقت الشاشة؟",
    "The brand of the device being used": "العلامة التجارية للجهاز المستخدم",
    "The context, content, and level of connection during screen use": "السياق والمحتوى ومستوى التواصل أثناء استخدام الشاشة",
    "Whether the screen is a phone or a tablet": "ما إذا كانت الشاشة هاتفاً أو جهازاً لوحياً",
    "The time of day when screens are used": "الوقت من اليوم الذي تُستخدم فيه الشاشات",
    'What is a "media ecology" approach to screen time?': 'ما هو نهج "البيئة الإعلامية" لوقت الشاشة؟',
    "Eliminating all screens from the home": "إزالة جميع الشاشات من المنزل",
    "Using only eco-friendly devices": "استخدام أجهزة صديقة للبيئة فقط",
    "Thinking holistically about how screens fit into daily family life": "التفكير بشكل شامل في كيفية تناسب الشاشات مع الحياة اليومية للأسرة",
    "Limiting screen time to educational content only": "تقييد وقت الشاشة بالمحتوى التعليمي فقط",
    "Why is co-viewing important for younger children?": "لماذا تعتبر المشاهدة المشتركة مهمة للأطفال الصغار؟",
    "Because children cannot operate devices alone": "لأن الأطفال لا يستطيعون تشغيل الأجهزة بمفردهم",
    "It builds language skills and helps children process content": "تبني مهارات اللغة وتساعد الأطفال على معالجة المحتوى",
    "It is not important -- children learn better independently": "ليست مهمة -- الأطفال يتعلمون بشكل أفضل مستقلاً",
    "Because parents need to monitor for inappropriate content at all times": "لأن الوالدين يحتاجون لمراقبة المحتوى غير المناسب دائماً",
    "What is the most powerful way to teach children healthy technology habits?": "ما الطريقة الأقوى لتعليم الأطفال عادات تكنولوجيا صحية؟",
    "Installing parental control software": "تثبيت برامج الرقابة الأبوية",
    "Banning all devices until a certain age": "حظر جميع الأجهزة حتى سن معين",
    "Modeling the relationship with technology you want them to have": "أن تكون نموذجاً للعلاقة مع التكنولوجيا التي تريدهم أن يمتلكوها",
    "Lecturing them about the dangers of screens": "إلقاء المحاضرات عليهم حول مخاطر الشاشات",
    "My child has intense tantrums when screen time ends. What can I do?": "طفلي يصاب بنوبات غضب شديدة عندما ينتهي وقت الشاشة. ماذا أفعل؟",
    "How much screen time is appropriate for my child's age?": "كم من وقت الشاشة مناسب لعمر طفلي؟",
    "Differentiate between passive screen consumption and active, connected screen use": "ميّز بين الاستهلاك السلبي للشاشة والاستخدام النشط والمتصل",
    "Create a family media agreement collaboratively with your children": "أنشئ اتفاقية إعلامية عائلية بالتعاون مع أطفالك",
    "Model healthy personal technology habits for your family": "كن نموذجاً لعادات تكنولوجية شخصية صحية لعائلتك",
    "Association Between Screen Time and Children's Performance on a Developmental Screening Test": "العلاقة بين وقت الشاشة وأداء الأطفال في اختبار الفحص التنموي",
    "Mobile and Interactive Media Use by Young Children: The Good, the Bad, and the Unknown": "استخدام الأطفال الصغار للوسائط المحمولة والتفاعلية: الجيد والسيئ والمجهول",
    "The Tablet at Dinner": "الجهاز اللوحي على العشاء",
    "Screen Time: Active vs. Passive": "وقت الشاشة: نشط مقابل سلبي",
    "Categorize each screen activity as Active Engagement or Passive Consumption.": "صنّف كل نشاط شاشة كتفاعل نشط أو استهلاك سلبي.",
    "Video-calling a grandparent": "مكالمة فيديو مع الأجداد",
    "Endlessly scrolling through videos": "التمرير اللانهائي عبر مقاطع الفيديو",
    "Creating digital art together": "إنشاء فن رقمي معاً",
    "Watching shows alone without interaction": "مشاهدة البرامج بمفرده دون تفاعل",
    "Co-viewing a documentary and discussing it": "مشاهدة فيلم وثائقي معاً ومناقشته",
    "Family Screen Health Check": "فحص صحة الشاشة العائلية",
    "Screen time in our home does not displace physical play, family connection, or sleep.": "وقت الشاشة في منزلنا لا يحل محل اللعب الجسدي أو التواصل العائلي أو النوم.",
    "Screen Imbalance": "خلل في توازن الشاشة",
    "Working Toward Balance": "العمل نحو التوازن",
    "Healthy Media Ecology": "بيئة إعلامية صحية",
    "The Screen Time Spectrum": "طيف وقت الشاشة",
    "Passive Consumption": "الاستهلاك السلبي",
    "Scrolling, watching alone, no interaction": "التمرير والمشاهدة بمفرده ولا تفاعل",
    "Solo Active Use": "الاستخدام النشط المنفرد",
    "Educational apps, creating content independently": "تطبيقات تعليمية وإنشاء محتوى بشكل مستقل",
    "Shared Engagement": "التفاعل المشترك",
    "Co-viewing with discussion, playing games together": "المشاهدة المشتركة مع النقاش ولعب الألعاب معاً",
    "Connected & Creative": "متصل ومبدع",
    "Video calls with family, collaborative digital projects": "مكالمات فيديو مع العائلة ومشاريع رقمية تعاونية",

    # MODULE 2.3: Sibling Dynamics
    "What is the difference between treating children equally and equitably?": "ما الفرق بين معاملة الأطفال بالتساوي وبالإنصاف؟",
    "Equal means the same for everyone; equitable means giving each child what they need": "المساواة تعني نفس الشيء للجميع؛ الإنصاف يعني إعطاء كل طفل ما يحتاجه",
    "They mean the same thing": "يعنيان نفس الشيء",
    "Equitable means favoring one child over another": "الإنصاف يعني تفضيل طفل على آخر",
    "Equal treatment is always better than equitable treatment": "المعاملة المتساوية دائماً أفضل من المنصفة",
    "Why should parents avoid playing judge during sibling conflicts?": "لماذا يجب على الوالدين تجنب لعب دور القاضي أثناء خلافات الإخوة؟",
    "Because parents are always biased toward one child": "لأن الوالدين دائماً منحازون لطفل واحد",
    "Because coaching children to resolve conflicts builds their problem-solving skills": "لأن توجيه الأطفال لحل النزاعات يبني مهاراتهم في حل المشكلات",
    "Because sibling conflicts are never serious enough to intervene": "لأن خلافات الإخوة ليست خطيرة بما يكفي للتدخل",
    "Because children should fight without any adult guidance": "لأن الأطفال يجب أن يتشاجروا بدون توجيه",
    "How does dedicated one-on-one time reduce sibling rivalry?": "كيف يقلل الوقت المخصص لكل طفل من التنافس بين الإخوة؟",
    "It keeps siblings physically separated": "يبقي الإخوة منفصلين جسدياً",
    "It teaches children to prefer being alone": "يعلّم الأطفال تفضيل البقاء بمفردهم",
    "It meets each child's need for individual attention, reducing competition": "يلبي حاجة كل طفل للاهتمام الفردي مما يقلل المنافسة",
    "It does not actually reduce sibling rivalry": "لا يقلل فعلياً من التنافس بين الإخوة",
    "Why is comparing siblings harmful even when the comparison seems positive?": "لماذا المقارنة بين الإخوة ضارة حتى عندما تبدو إيجابية؟",
    "Comparisons create fixed roles that limit each child's identity": "المقارنات تخلق أدواراً ثابتة تحد من هوية كل طفل",
    "Positive comparisons are actually helpful for motivation": "المقارنات الإيجابية مفيدة فعلاً للتحفيز",
    "Children do not notice when they are being compared": "الأطفال لا يلاحظون عندما تتم مقارنتهم",
    "Comparisons only matter if they are negative": "المقارنات مهمة فقط إذا كانت سلبية",
    "My older child is always mean to the younger one. What can I do?": "طفلي الأكبر دائماً قاسٍ مع الأصغر. ماذا أفعل؟",
    "Should I intervene every time my children argue?": "هل يجب أن أتدخل في كل مرة يتشاجر فيها أطفالي؟",
    "Distinguish between equal and equitable treatment of siblings": "ميّز بين المعاملة المتساوية والمنصفة للإخوة",
    "Coach children through sibling conflicts rather than judging who is right": "وجّه الأطفال خلال خلافات الإخوة بدلاً من الحكم على من هو محق",
    "Implement dedicated one-on-one time with each child to reduce rivalry": "طبّق وقتاً مخصصاً مع كل طفل لتقليل التنافس",
    "Learning How to Be a Sibling: Cross-Section and Longitudinal Perspectives": "تعلّم كيف تكون أخاً: منظورات مقطعية وطولية",
    "The Third Rail of Family Systems: Sibling Relationships, Mental and Behavioral Health": "السكة الثالثة لأنظمة الأسرة: علاقات الإخوة والصحة النفسية والسلوكية",
    "The Toy Tug-of-War": "شد الحبل على اللعبة",
    "Sibling Dynamics Concepts": "مفاهيم ديناميكيات الإخوة",
    "Match each concept with its correct explanation.": "طابق كل مفهوم مع شرحه الصحيح.",
    "Equal treatment": "المعاملة المتساوية",
    "Giving every child the exact same thing": "إعطاء كل طفل نفس الشيء بالضبط",
    "Equitable treatment": "المعاملة المنصفة",
    "Giving each child what they individually need": "إعطاء كل طفل ما يحتاجه بشكل فردي",
    "One-on-one time": "وقت فردي",
    "Dedicated, unshared parent time that reduces competition": "وقت والدي مخصص وغير مشترك يقلل المنافسة",
    "Conflict coaching": "توجيه حل النزاعات",
    "Guiding children to resolve disputes themselves": "توجيه الأطفال لحل خلافاتهم بأنفسهم",
    "Sibling Fairness Reflection": "تأمل في عدالة الإخوة",
    "I give each of my children dedicated one-on-one time regularly.": "أعطي كلاً من أطفالي وقتاً فردياً مخصصاً بانتظام.",
    "Shared Attention Only": "اهتمام مشترك فقط",
    "Occasional Individual Time": "وقت فردي من حين لآخر",
    "Regular Individual Connection": "تواصل فردي منتظم",
    "The Sibling Conflict Intervention Spectrum": "طيف التدخل في خلافات الإخوة",
    "Observe": "راقب",
    "Minor bickering: let them practice resolving it": "مشاحنات بسيطة: دعهم يتدربون على حلها",
    "Coach": "وجّه",
    "Moderate conflict: guide from the sidelines": "خلاف متوسط: وجّه من الخطوط الجانبية",
    "Mediate": "توسّط",
    "Escalating conflict: step in to help resolve": "خلاف متصاعد: تدخل للمساعدة في الحل",
    "Separate": "افصل",
    "Physical aggression or bullying: intervene immediately": "عدوان جسدي أو تنمر: تدخل فوراً",

    # MODULE 2.4: Supporting Anxious Children
    "How does childhood anxiety often differ from adult anxiety?": "كيف يختلف قلق الأطفال غالباً عن قلق الكبار؟",
    "Children describe their worries in more detail than adults": "الأطفال يصفون مخاوفهم بتفصيل أكثر من الكبار",
    "Children often express anxiety through physical symptoms and behavioral changes": "غالباً ما يعبّر الأطفال عن القلق من خلال الأعراض الجسدية والتغيرات السلوكية",
    "Childhood anxiety is never serious": "قلق الأطفال ليس خطيراً أبداً",
    "Adults experience more physical symptoms than children": "الكبار يختبرون أعراضاً جسدية أكثر من الأطفال",
    "What is graduated exposure?": "ما هو التعرض التدريجي؟",
    "Forcing a child to face their biggest fear immediately": "إجبار الطفل على مواجهة أكبر مخاوفه فوراً",
    "Removing all sources of anxiety from a child's life": "إزالة جميع مصادر القلق من حياة الطفل",
    "Supporting a child in gradually approaching feared situations one small step at a time": "دعم الطفل في الاقتراب تدريجياً من المواقف المخيفة خطوة صغيرة في كل مرة",
    "Exposing children to frightening media to build resilience": "تعريض الأطفال لوسائط مخيفة لبناء المرونة",
    'What is the purpose of a "worry time" ritual?': 'ما الغرض من طقس "وقت القلق"؟',
    "To make children worry more by thinking about their fears": "لجعل الأطفال يقلقون أكثر بالتفكير في مخاوفهم",
    "To create a safe container for worries and teach children that worries can wait": "لإنشاء حاوية آمنة للمخاوف وتعليم الأطفال أن المخاوف يمكن أن تنتظر",
    "To eliminate all worries permanently": "للقضاء على جميع المخاوف بشكل دائم",
    "To prove to children that their worries are not important": "لإثبات للأطفال أن مخاوفهم ليست مهمة",
    "When should a parent seek professional help for a child's anxiety?": "متى يجب على الوالد طلب المساعدة المهنية لقلق الطفل؟",
    "Only if the child asks for help": "فقط إذا طلب الطفل المساعدة",
    "When anxiety significantly impacts daily functioning, school, or family life": "عندما يؤثر القلق بشكل كبير على الأداء اليومي أو المدرسة أو الحياة الأسرية",
    "Never -- all childhood anxiety resolves on its own": "أبداً -- كل قلق الطفولة يزول من تلقاء نفسه",
    "Only if the child has a diagnosed anxiety disorder": "فقط إذا كان لدى الطفل اضطراب قلق مُشخّص",
    "Is my child's anxiety my fault?": "هل قلق طفلي خطئي؟",
    "Should I avoid all situations that make my child anxious?": "هل يجب أن أتجنب جميع المواقف التي تجعل طفلي قلقاً؟",
    "Recognize the physical and behavioral signs of anxiety in children": "تعرّف على العلامات الجسدية والسلوكية للقلق عند الأطفال",
    "Validate anxious feelings without reinforcing avoidance patterns": "أكّد على المشاعر القلقة دون تعزيز أنماط التجنب",
    "Teach concrete coping tools: belly breathing, grounding, and worry maps": "علّم أدوات تكيّف ملموسة: التنفس البطني والتأريض وخرائط القلق",
    "Know when to seek professional support for childhood anxiety": "اعرف متى تطلب الدعم المهني لقلق الطفولة",
    "Parent Training for Childhood Anxiety Disorders: SPACE Program": "تدريب الوالدين لاضطرابات قلق الطفولة: برنامج SPACE",
    "Prevention and Early Intervention for Anxiety Disorders in Inhibited Preschool Children": "الوقاية والتدخل المبكر لاضطرابات القلق عند أطفال ما قبل المدرسة",
    "The School Drop-Off Cling": "التشبث عند التوصيل إلى المدرسة",
    "Anxiety Coping Tools": "أدوات التعامل مع القلق",
    "Match each coping tool with its technique.": "طابق كل أداة تكيّف مع تقنيتها.",
    "Belly Breathing": "التنفس البطني",
    "Place hand on stomach and breathe slowly until it rises": "ضع يدك على بطنك وتنفس ببطء حتى يرتفع",
    "5-4-3-2-1 Grounding": "تأريض ٥-٤-٣-٢-١",
    "Name things you see, hear, touch, smell, and taste": "سمِّ أشياء تراها وتسمعها وتلمسها وتشمها وتتذوقها",
    "Worry Map": "خريطة القلق",
    "Draw where anxiety is felt in the body": "ارسم أين يُحَسّ بالقلق في الجسم",
    "Worry Time": "وقت القلق",
    "Dedicated 10-minute window for sharing all worries": "نافذة مخصصة مدتها ١٠ دقائق لمشاركة جميع المخاوف",
    "Graduated Exposure": "التعرض التدريجي",
    "Approaching feared situations in small, manageable steps": "الاقتراب من المواقف المخيفة بخطوات صغيرة يمكن التحكم بها",
    "Anxiety Support Self-Check": "فحص ذاتي لدعم القلق",
    "When my child is anxious, I validate their feelings without rushing to rescue them from the situation.": "عندما يكون طفلي قلقاً أؤكد على مشاعره دون التسرع في إنقاذه من الموقف.",
    "Rescue Mode": "وضع الإنقاذ",
    "Learning to Balance": "تعلّم التوازن",
    "Supportive Coach": "مدرب داعم",
    "The Anxiety Iceberg": "جبل جليد القلق",
    "Visible Signs": "علامات مرئية",
    "Clinginess, irritability, avoidance, stomachaches, sleep issues": "التشبث والانفعال والتجنب وآلام المعدة ومشاكل النوم",
    "Anxious Thoughts": "أفكار قلقة",
    "Body Sensations": "أحاسيس جسدية",
    "Racing heart, tight chest, butterflies, sweaty palms": "قلب متسارع وصدر مشدود وفراشات في البطن وأيدٍ متعرقة",
    "Underlying Needs": "احتياجات كامنة",
    "Safety, predictability, reassurance, connection": "الأمان والقابلية للتوقع والطمأنينة والتواصل",

    # MODULE 2.5: Culturally Rooted Parenting
    'What does it mean to be a "cultural bridge" for your children?': 'ماذا يعني أن تكون "جسراً ثقافياً" لأطفالك؟',
    "Forcing children to follow only traditional practices": "إجبار الأطفال على اتباع الممارسات التقليدية فقط",
    "Helping children appreciate their heritage while navigating broader society": "مساعدة الأطفال على تقدير تراثهم مع التعامل مع المجتمع الأوسع",
    "Abandoning cultural traditions to fit into the new environment": "التخلي عن التقاليد الثقافية للتأقلم مع البيئة الجديدة",
    "Keeping children isolated from other cultures": "عزل الأطفال عن الثقافات الأخرى",
    "How should parents respond when children question cultural practices?": "كيف يجب أن يستجيب الوالدان عندما يتساءل الأطفال عن الممارسات الثقافية؟",
    "See it as disrespect and shut down the conversation": "اعتبره عدم احترام وأنهِ المحادثة",
    "Invite dialogue that honors both tradition and growth": "ادعُ إلى حوار يحترم التقاليد والنمو معاً",
    "Immediately abandon the practice to keep peace": "تخلَّ عن الممارسة فوراً للحفاظ على السلام",
    "Ignore the question and change the subject": "تجاهل السؤال وغيّر الموضوع",
    "What is the relationship between cultural identity and resilience in children?": "ما العلاقة بين الهوية الثقافية والمرونة عند الأطفال؟",
    "Cultural identity has no impact on resilience": "الهوية الثقافية ليس لها تأثير على المرونة",
    "Strong cultural identity makes children less adaptable": "الهوية الثقافية القوية تجعل الأطفال أقل قدرة على التكيف",
    "Children who know their cultural roots tend to be more resilient and confident": "الأطفال الذين يعرفون جذورهم الثقافية يميلون لأن يكونوا أكثر مرونة وثقة",
    "Only one culture should be emphasized to avoid confusion": "يجب التركيز على ثقافة واحدة فقط لتجنب الارتباك",
    'What does "integration, not assimilation" mean in the context of culturally rooted parenting?': 'ماذا يعني "الاندماج وليس الذوبان" في سياق التربية المتجذرة ثقافياً؟',
    "Completely replacing your cultural identity with the new culture": "استبدال هويتك الثقافية بالكامل بالثقافة الجديدة",
    "Holding both cultural worlds with grace rather than abandoning one for the other": "الاحتفاظ بكلا العالمين الثقافيين بأناقة بدلاً من التخلي عن أحدهما للآخر",
    "Rejecting the new culture entirely": "رفض الثقافة الجديدة بالكامل",
    "Keeping cultures completely separate with no overlap": "إبقاء الثقافات منفصلة تماماً بدون تداخل",
    "My children are embarrassed by our cultural traditions. How do I handle this?": "أطفالي يشعرون بالحرج من تقاليدنا الثقافية. كيف أتعامل مع هذا؟",
    "How do I navigate cultural expectations from extended family that I disagree with?": "كيف أتعامل مع التوقعات الثقافية من العائلة الممتدة التي أختلف معها؟",
    "We are an interfaith or intercultural couple. How do we decide which traditions to follow?": "نحن زوجان من ديانتين أو ثقافتين مختلفتين. كيف نقرر أي التقاليد نتبع؟",
    "Serve as a cultural bridge for your children between heritage and broader society": "كن جسراً ثقافياً لأطفالك بين التراث والمجتمع الأوسع",
    "Navigate cultural tension around discipline by preserving values while evolving methods": "تعامل مع التوتر الثقافي حول التأديب بالحفاظ على القيم مع تطوير الأساليب",
    "Create open dialogue when children question cultural practices": "أنشئ حواراً مفتوحاً عندما يتساءل الأطفال عن الممارسات الثقافية",
    "Immigration, Acculturation, and Adaptation": "الهجرة والتثاقف والتكيف",
    "Ethnic Identity During Adolescence: A Process-Oriented Approach": "الهوية العرقية خلال المراهقة: نهج موجه نحو العملية",
    "The Cultural Clash at School": "الصدام الثقافي في المدرسة",
    "Acculturation Strategies": "استراتيجيات التثاقف",
    "Match each acculturation strategy with its description.": "طابق كل استراتيجية تثاقف مع وصفها.",
    "Integration": "الاندماج",
    "Maintaining heritage while engaging with host culture": "الحفاظ على التراث مع المشاركة في ثقافة البلد المضيف",
    "Assimilation": "الذوبان",
    "Adopting host culture while abandoning heritage": "تبني ثقافة البلد المضيف مع التخلي عن التراث",
    "Separation": "الانفصال",
    "Maintaining heritage while rejecting host culture": "الحفاظ على التراث مع رفض ثقافة البلد المضيف",
    "Cultural Bridge": "الجسر الثقافي",
    "Helping children navigate between both worlds": "مساعدة الأطفال على التنقل بين العالمين",
    "Cultural Integration Reflection": "تأمل في الاندماج الثقافي",
    "I actively share my cultural heritage with my children through stories, food, language, and traditions.": "أشارك بنشاط تراثي الثقافي مع أطفالي من خلال القصص والطعام واللغة والتقاليد.",
    "Cultural Disconnect": "انفصال ثقافي",
    "Growing Roots": "جذور نامية",
    "Deeply Rooted": "متجذر بعمق",
    "High heritage + high host culture engagement. Best outcomes.": "تراث عالٍ + مشاركة عالية في ثقافة البلد المضيف. أفضل النتائج.",
    "Low heritage + high host culture. Heritage loss.": "تراث منخفض + ثقافة بلد مضيف عالية. فقدان التراث.",
    "High heritage + low host culture. Cultural isolation.": "تراث عالٍ + ثقافة بلد مضيف منخفضة. عزلة ثقافية.",
    "Marginalization": "التهميش",
    "Low heritage + low host culture. Identity loss.": "تراث منخفض + ثقافة بلد مضيف منخفضة. فقدان الهوية.",

    # MODULE 3.1-3.5: All remaining titles, labels, etc.
    "What are the four key areas of emotional intelligence in children?": "ما المجالات الأربعة الرئيسية للذكاء العاطفي عند الأطفال؟",
    "Reading, writing, math, and science": "القراءة والكتابة والرياضيات والعلوم",
    "Obedience, politeness, patience, and gratitude": "الطاعة والأدب والصبر والامتنان",
    "Emotional awareness, regulation, empathy, and social skills": "الوعي العاطفي والتنظيم والتعاطف والمهارات الاجتماعية",
    "Happiness, calmness, friendliness, and cooperation": "السعادة والهدوء والود والتعاون",
    "Why is having a wide emotional vocabulary important for children?": "لماذا يعتبر امتلاك مفردات عاطفية واسعة مهماً للأطفال؟",
    "It helps them score better on vocabulary tests": "يساعدهم في الحصول على درجات أفضل في اختبارات المفردات",
    "It allows them to communicate their inner world more precisely": "يسمح لهم بالتواصل مع عالمهم الداخلي بدقة أكبر",
    "It is not important -- basic emotion words are sufficient": "ليس مهماً -- الكلمات العاطفية الأساسية كافية",
    "It helps them argue more effectively with siblings": "يساعدهم في الجدال بشكل أكثر فعالية مع الإخوة",
    "What is the most effective way for children to learn emotional regulation?": "ما الطريقة الأكثر فعالية لتعلم الأطفال التنظيم العاطفي؟",
    "Being told to control their emotions": "إخبارهم بالتحكم في مشاعرهم",
    "Watching their parents model regulation strategies": "مشاهدة والديهم يطبقون استراتيجيات التنظيم",
    "Attending special classes outside the home": "حضور فصول خاصة خارج المنزل",
    "Reading books about emotions independently": "قراءة كتب عن المشاعر بشكل مستقل",
    "Why should parents be mindful of gendered messages about emotions?": "لماذا يجب على الوالدين الانتباه للرسائل الجندرية حول المشاعر؟",
    "Because boys and girls experience different emotions": "لأن الأولاد والبنات يختبرون مشاعر مختلفة",
    "Because gendered messages limit children and every child deserves full emotional freedom": "لأن الرسائل الجندرية تحد من الأطفال وكل طفل يستحق حرية عاطفية كاملة",
    "Because only girls need emotional intelligence": "لأن البنات فقط يحتجن الذكاء العاطفي",
    "Gendered messages are not a real concern in modern parenting": "الرسائل الجندرية ليست مصدر قلق حقيقي في التربية الحديثة",
    "My child seems to lack empathy. Is this normal?": "يبدو أن طفلي يفتقر إلى التعاطف. هل هذا طبيعي؟",
    "How do I build emotional intelligence in a child who resists talking about feelings?": "كيف أبني الذكاء العاطفي عند طفل يقاوم الحديث عن المشاعر؟",
    "Build the four pillars of emotional intelligence: awareness, regulation, empathy, and social skills": "ابنِ الركائز الأربع للذكاء العاطفي: الوعي والتنظيم والتعاطف والمهارات الاجتماعية",
    "Expand your family's emotional vocabulary beyond basic emotion words": "وسّع مفردات عائلتك العاطفية لتتجاوز كلمات المشاعر الأساسية",
    "Identify and address gendered messages about emotions in your family": "حدّد وعالج الرسائل الجندرية حول المشاعر في عائلتك",
    "The Intelligence of Emotional Intelligence": "ذكاء الذكاء العاطفي",
    "Emotional Intelligence and Its Relation to Everyday Behaviour": "الذكاء العاطفي وعلاقته بالسلوك اليومي",
    "The Playground Rejection": "الرفض في الملعب",
    "Four Pillars of Emotional Intelligence": "الركائز الأربع للذكاء العاطفي",
    "Match each pillar with an example of how to build it at home.": "طابق كل ركيزة مع مثال عن كيفية بنائها في المنزل.",
    "Emotional Awareness": "الوعي العاطفي",
    "Emotional Regulation": "التنظيم العاطفي",
    "Empathy": "التعاطف",
    "Social Skills": "المهارات الاجتماعية",
    "Emotional Literacy at Home": "الوعي العاطفي في المنزل",
    'My family regularly discusses emotions openly using a wide vocabulary beyond "happy," "sad," and "angry."': 'عائلتنا تناقش المشاعر بانتظام وبشكل مفتوح باستخدام مفردات واسعة تتجاوز "سعيد" و"حزين" و"غاضب".',
    "Limited Emotional Language": "لغة عاطفية محدودة",
    "Developing Literacy": "تطوير الوعي",
    "Emotionally Literate Home": "منزل واعٍ عاطفياً",
    "The Four Pillars of Emotional Intelligence": "الركائز الأربع للذكاء العاطفي",
    "Recognizing and naming feelings": "التعرف على المشاعر وتسميتها",
    "Managing big feelings with healthy strategies": "إدارة المشاعر الكبيرة باستراتيجيات صحية",
    "Understanding and sharing others' feelings": "فهم مشاعر الآخرين والمشاركة فيها",
    "Navigating relationships and resolving conflicts": "التنقل في العلاقات وحل النزاعات",

    # MODULE 3.2-3.5 titles, labels, scenarios etc.
    "How do children typically process transitions differently from adults?": "كيف يعالج الأطفال عادة المراحل الانتقالية بشكل مختلف عن الكبار؟",
    "Children understand the logical reasons for change better than adults": "الأطفال يفهمون الأسباب المنطقية للتغيير أفضل من الكبار",
    "Children tend to process change through the lens of loss": "يميل الأطفال إلى معالجة التغيير من خلال عدسة الخسارة",
    "Children are not affected by transitions if they are young enough": "الأطفال لا يتأثرون بالانتقالات إذا كانوا صغاراً بما يكفي",
    "Children and adults process transitions in the same way": "الأطفال والكبار يعالجون الانتقالات بنفس الطريقة",
    "Why is maintaining familiar routines important during transitions?": "لماذا يعتبر الحفاظ على الروتين المألوف مهماً أثناء الانتقالات؟",
    "Because change should be completely avoided for children": "لأن التغيير يجب تجنبه تماماً للأطفال",
    "Familiar routines serve as anchors of stability in a shifting landscape": "الروتين المألوف يكون بمثابة مراسي استقرار في مشهد متغير",
    "Because children cannot adapt to any new routines": "لأن الأطفال لا يستطيعون التكيف مع أي روتين جديد",
    "Routines are not important during transitions": "الروتين ليس مهماً أثناء الانتقالات",
    "What should you do when you do not have all the answers about an upcoming change?": "ماذا يجب أن تفعل عندما لا تملك جميع الإجابات عن تغيير قادم؟",
    "Make up answers to keep your child calm": "اختلق إجابات لإبقاء طفلك هادئاً",
    "Avoid discussing the change until you have all the details": "تجنب مناقشة التغيير حتى تملك جميع التفاصيل",
    "Be honest about what you know and what you do not yet know": "كن صادقاً بشأن ما تعرفه وما لا تعرفه بعد",
    "Tell children everything will be perfect": "أخبر الأطفال أن كل شيء سيكون مثالياً",
    "Why is it helpful to share your own feelings about a transition with your child?": "لماذا من المفيد مشاركة مشاعرك عن الانتقال مع طفلك؟",
    "It makes the child responsible for the parent's emotions": "يجعل الطفل مسؤولاً عن مشاعر الوالد",
    "It models emotional honesty and teaches that feelings are manageable": "يكون نموذجاً للصدق العاطفي ويعلّم أن المشاعر يمكن إدارتها",
    "Parents should always hide their feelings from children": "يجب على الوالدين دائماً إخفاء مشاعرهم عن الأطفال",
    "It gives children permission to avoid the transition": "يمنح الأطفال إذناً لتجنب الانتقال",
    "My child is regressing during a family transition. Should I be worried?": "طفلي يتراجع أثناء انتقال عائلي. هل يجب أن أقلق؟",
    "How much should I tell my young child about a family separation or divorce?": "كم يجب أن أخبر طفلي الصغير عن انفصال أو طلاق عائلي؟",
    "Maintain emotional availability and familiar routines during family transitions": "حافظ على التوفر العاطفي والروتين المألوف أثناء الانتقالات العائلية",
    "Communicate honestly about change in age-appropriate ways": "تواصل بصدق عن التغيير بطرق مناسبة للعمر",
    "Recognize signs that a child may need additional professional support during transitions": "تعرّف على علامات أن الطفل قد يحتاج دعماً مهنياً إضافياً أثناء الانتقالات",
    "Ordinary Magic: Resilience Processes in Development": "السحر العادي: عمليات المرونة في النمو",
    "Long-Term Effects of Prevention Programs on Divorce Adjustment": "التأثيرات طويلة المدى لبرامج الوقاية على التكيف مع الطلاق",
    "The Big Move": "الانتقال الكبير",
    "Supporting Children Through Transitions": "دعم الأطفال خلال المراحل الانتقالية",
    "Match each strategy with the transition challenge it addresses.": "طابق كل استراتيجية مع تحدي الانتقال الذي تعالجه.",
    "Maintaining bedtime rituals": "الحفاظ على طقوس وقت النوم",
    "Provides stability when external circumstances change": "يوفر الاستقرار عندما تتغير الظروف الخارجية",
    "Giving age-appropriate choices": "منح خيارات مناسبة للعمر",
    "Reduces feelings of helplessness during change": "يقلل مشاعر العجز أثناء التغيير",
    "Honest communication": "التواصل الصادق",
    "Builds trust through uncertain times": "يبني الثقة خلال الأوقات غير المؤكدة",
    "Tolerating regression": "تقبّل التراجع",
    "Recognizes that backward steps are normal during major change": "يدرك أن الخطوات الخلفية طبيعية أثناء التغيير الكبير",
    "Transition Navigation Skills": "مهارات التنقل في المراحل الانتقالية",
    "During family changes, I maintain routines and stay emotionally available even when I am stressed.": "أثناء التغييرات العائلية أحافظ على الروتين وأبقى متاحاً عاطفياً حتى عندما أكون متوتراً.",
    "Overwhelmed by Change": "مغمور بالتغيير",
    "Building Stability": "بناء الاستقرار",
    "Steady Through Change": "ثابت خلال التغيير",
    "The Transition Support Framework": "إطار دعم المراحل الانتقالية",
    "Change Occurs": "يحدث تغيير",
    "A transition enters the family system": "يدخل انتقال إلى نظام الأسرة",
    "Communicate Honestly": "تواصل بصدق",
    "Age-appropriate honesty about what is happening": "صدق مناسب للعمر حول ما يحدث",
    "Maintain Anchors": "حافظ على المراسي",
    "Keep familiar routines and rituals stable": "حافظ على استقرار الروتين والطقوس المألوفة",
    "Give Agency": "امنح الاستقلالية",
    "Offer age-appropriate choices within the change": "قدّم خيارات مناسبة للعمر ضمن التغيير",
    "Stay Available": "ابقَ متاحاً",
    "Be emotionally present through big feelings": "كن حاضراً عاطفياً خلال المشاعر الكبيرة",

    # Module 3.3
    "What is family resilience?": "ما هي مرونة الأسرة؟",
    "The absence of any difficulty in family life": "غياب أي صعوبة في الحياة الأسرية",
    "The capacity to withstand and recover from challenges, growing stronger together": "القدرة على تحمل التحديات والتعافي منها والنمو أقوى معاً",
    "Being able to avoid all conflict within the family": "القدرة على تجنب جميع النزاعات داخل الأسرة",
    "Having enough financial resources to solve all problems": "امتلاك موارد مالية كافية لحل جميع المشكلات",
    "What are the key protective factors of resilient families?": "ما عوامل الحماية الرئيسية للأسر المرنة؟",
    "Wealth, education, and social status": "الثروة والتعليم والمكانة الاجتماعية",
    "Shared beliefs, open communication, flexibility, and connectedness": "المعتقدات المشتركة والتواصل المفتوح والمرونة والترابط",
    "Strict rules, punishment, and obedience": "القواعد الصارمة والعقاب والطاعة",
    "Avoiding all risk and change": "تجنب جميع المخاطر والتغيير",
    "Why are family meetings valuable for building resilience?": "لماذا تعتبر اجتماعات الأسرة قيّمة لبناء المرونة؟",
    "They allow parents to lecture children about behavior": "تسمح للوالدين بإلقاء المحاضرات على الأطفال حول السلوك",
    "They teach children that their voice matters and problems can be solved together": "تعلّم الأطفال أن صوتهم مهم وأن المشكلات يمكن حلها معاً",
    "They are only useful for families in crisis": "مفيدة فقط للأسر في أزمة",
    "They replace the need for professional help": "تحل محل الحاجة إلى المساعدة المهنية",
    "Why should parents not shield children from all hardship?": "لماذا لا يجب على الوالدين حماية الأطفال من جميع المشقات؟",
    "Because children need to suffer to grow": "لأن الأطفال يحتاجون للمعاناة للنمو",
    "Because shielding from all hardship robs children of the chance to develop resilience": "لأن الحماية من جميع المشقات تحرم الأطفال من فرصة تطوير المرونة",
    "Because parents should not care about their children's comfort": "لأن الوالدين لا يجب أن يهتموا براحة أطفالهم",
    "Because children are naturally resilient and do not need any support": "لأن الأطفال مرنون بطبيعتهم ولا يحتاجون أي دعم",
    "My family is going through a very difficult time right now. How do I build resilience when I am barely coping?": "عائلتي تمر بوقت صعب جداً الآن. كيف أبني المرونة وأنا بالكاد أتأقلم؟",
    "How do I build resilience in a single-parent family?": "كيف أبني المرونة في أسرة وحيدة الوالد؟",
    "Identify the four key protective factors of resilient families": "حدّد عوامل الحماية الأربعة الرئيسية للأسر المرنة",
    "Conduct a family meeting that celebrates strengths and addresses challenges collaboratively": "أجرِ اجتماعاً عائلياً يحتفي بنقاط القوة ويعالج التحديات بشكل تعاوني",
    "Build a positive family identity and shared narrative of resilience": "ابنِ هوية عائلية إيجابية وسردية مشتركة عن المرونة",
    "Family Resilience: A Framework for Clinical Practice": "مرونة الأسرة: إطار للممارسة السريرية",
    "Understanding Family Resilience": "فهم مرونة الأسرة",
    "The Family Financial Setback": "النكسة المالية العائلية",
    "Family Resilience Protective Factors": "عوامل الحماية لمرونة الأسرة",
    "Match each protective factor with an example of how it looks in family life.": "طابق كل عامل حماية مع مثال عن كيف يبدو في الحياة الأسرية.",
    "Shared Belief System": "نظام معتقدات مشترك",
    '"Our family has been through hard things and we always find our way"': '"عائلتنا مرت بأمور صعبة ونجد دائماً طريقنا"',
    "Open Communication": "تواصل مفتوح",
    "Regular family meetings where every voice matters": "اجتماعات عائلية منتظمة حيث كل صوت مهم",
    "Organizational Flexibility": "مرونة تنظيمية",
    "Adjusting roles and routines when circumstances change": "تعديل الأدوار والروتين عندما تتغير الظروف",
    "Connectedness": "الترابط",
    "Strong bonds within the family and support from community": "روابط قوية داخل الأسرة ودعم من المجتمع",
    "Family Resilience Assessment": "تقييم مرونة الأسرة",
    "Our family has a shared story about who we are and what we can get through together.": "عائلتنا لديها قصة مشتركة عن من نحن وما يمكننا تجاوزه معاً.",
    "Story Needed": "بحاجة إلى قصة",
    "Emerging Narrative": "سردية ناشئة",
    "Strong Family Identity": "هوية عائلية قوية",
    "Four Pillars of Family Resilience": "الركائز الأربع لمرونة الأسرة",
    "Shared Beliefs": "معتقدات مشتركة",
    "Making meaning together and maintaining hope": "صنع المعنى معاً والحفاظ على الأمل",
    "Honest, regular, collaborative dialogue": "حوار صادق ومنتظم وتعاوني",
    "Flexibility": "المرونة",
    "Adapting roles, routines, and approaches": "تكييف الأدوار والروتين والمناهج",
    "Strong internal bonds and community support": "روابط داخلية قوية ودعم مجتمعي",

    # Module 3.4
    "What does research show about the relationship between conflict and secure attachment?": "ماذا تُظهر الأبحاث عن العلاقة بين النزاع والتعلق الآمن؟",
    "Secure attachment requires the complete absence of conflict": "التعلق الآمن يتطلب غياب النزاع تماماً",
    "Consistent repair after conflict creates secure attachment": "الإصلاح المستمر بعد النزاع يخلق تعلقاً آمناً",
    "Conflict always damages attachment permanently": "النزاع يضر بالتعلق بشكل دائم دائماً",
    "Attachment is not affected by conflict or repair": "التعلق لا يتأثر بالنزاع أو الإصلاح",
    "What is the difference between a genuine repair and a deflecting apology?": "ما الفرق بين الإصلاح الحقيقي والاعتذار المراوغ؟",
    "A genuine repair includes excuses to help the child understand": "الإصلاح الحقيقي يتضمن أعذاراً لمساعدة الطفل على الفهم",
    "A genuine repair takes full ownership without blame or excuses": "الإصلاح الحقيقي يتحمل المسؤولية الكاملة بدون لوم أو أعذار",
    "A deflecting apology is more honest": "الاعتذار المراوغ أكثر صدقاً",
    "There is no difference between the two": "لا يوجد فرق بين الاثنين",
    "Does apologizing to your child undermine your authority?": "هل الاعتذار لطفلك يقوّض سلطتك؟",
    "Yes, children lose respect for parents who apologize": "نعم الأطفال يفقدون الاحترام للوالدين الذين يعتذرون",
    "No, it models strength, humility, and integrity while building trust": "لا إنه يكون نموذجاً للقوة والتواضع والنزاهة مع بناء الثقة",
    "Only if the apology is for something serious": "فقط إذا كان الاعتذار عن شيء خطير",
    "Parents should only apologize to other adults": "يجب على الوالدين الاعتذار للكبار فقط",
    "What should a complete repair conversation include?": "ماذا يجب أن تتضمن محادثة إصلاح كاملة؟",
    "An explanation of why the child was wrong": "شرح لماذا كان الطفل مخطئاً",
    "Accountability, warm reconnection, and a plan for what you will do differently": "المسؤولية وإعادة التواصل الدافئ وخطة لما ستفعله بشكل مختلف",
    "A promise that conflict will never happen again": "وعد بأن النزاع لن يحدث مرة أخرى",
    "A lecture about the importance of good behavior": "محاضرة عن أهمية السلوك الجيد",
    "I was never apologized to as a child. How do I start doing something that feels so unfamiliar?": "لم يُعتذر لي أبداً عندما كنت طفلاً. كيف أبدأ بفعل شيء يبدو غريباً جداً؟",
    "What if my child does not seem to care about the repair?": "ماذا لو بدا أن طفلي لا يهتم بالإصلاح؟",
    "Initiate repair conversations after conflict using the accountability-reconnection-plan framework": "ابدأ محادثات الإصلاح بعد النزاع باستخدام إطار المسؤولية-إعادة التواصل-الخطة",
    "Distinguish between genuine repair and deflecting apologies": "ميّز بين الإصلاح الحقيقي والاعتذارات المراوغة",
    "Normalize repair as a regular practice in your family culture": "اجعل الإصلاح ممارسة عادية في ثقافة عائلتك",
    "The Neurobehavioral and Social-Emotional Development of Infants and Children": "النمو العصبي السلوكي والاجتماعي العاطفي للرضع والأطفال",
    "A Secure Base: Parent-Child Attachment and Healthy Human Development": "قاعدة آمنة: التعلق بين الوالد والطفل والنمو الإنساني الصحي",
    "The Morning You Lost Your Temper": "الصباح الذي فقدت فيه أعصابك",
    "Components of Genuine Repair": "مكونات الإصلاح الحقيقي",
    "Match each repair component with its example.": "طابق كل مكون إصلاح مع مثاله.",
    "Accountability": "المسؤولية",
    '"I yelled, and that was not okay."': '"صرخت وهذا لم يكن مقبولاً."',
    "Empathy for the child": "التعاطف مع الطفل",
    '"That must have felt scary and unfair."': '"لا بد أن هذا شعر بالخوف وعدم العدالة."',
    "Forward plan": "خطة مستقبلية",
    '"Next time, I will take a breath before reacting."': '"في المرة القادمة سآخذ نفساً قبل الاستجابة."',
    "Reassurance": "الطمأنينة",
    '"I love you, and our relationship is safe."': '"أحبك وعلاقتنا آمنة."',
    "Repair Practice Self-Assessment": "التقييم الذاتي لممارسة الإصلاح",
    "After I handle a situation poorly with my child, I go back to them and genuinely apologize.": "بعد أن أتعامل مع موقف بشكل سيئ مع طفلي أعود إليه وأعتذر بصدق.",
    "Repair Hesitant": "متردد في الإصلاح",
    "Developing Repair Habit": "تطوير عادة الإصلاح",
    "Repair Champion": "بطل الإصلاح",
    "The Rupture-Repair Cycle": "دورة القطيعة والإصلاح",
    "Rupture Occurs": "تحدث قطيعة",
    "A moment of disconnection: yelling, harsh words, impatience": "لحظة انقطاع: صراخ أو كلمات قاسية أو نفاد صبر",
    "Parent Notices": "الوالد يلاحظ",
    "Awareness that something needs to be repaired": "الوعي بأن شيئاً يحتاج إلى إصلاح",
    "Both Calm Down": "كلاهما يهدأ",
    "Take space to regulate before repair": "خذ مساحة للتنظيم قبل الإصلاح",
    "Repair Conversation": "محادثة الإصلاح",
    "Accountability + empathy + plan + reassurance": "المسؤولية + التعاطف + الخطة + الطمأنينة",
    "Bond Strengthened": "الرابطة تتعزز",
    "Trust deepens: relationships survive difficulty": "الثقة تتعمق: العلاقات تنجو من الصعوبات",

    # Module 3.5
    "What is a parenting legacy?": "ما هو إرث التربية؟",
    "The amount of money you leave your children": "مقدار المال الذي تتركه لأطفالك",
    "The values, patterns, emotional skills, and memories you pass on to future generations": "القيم والأنماط والمهارات العاطفية والذكريات التي تمررها للأجيال القادمة",
    "The number of accomplishments your children achieve": "عدد الإنجازات التي يحققها أطفالك",
    "The house and possessions you provide": "المنزل والممتلكات التي توفرها",
    "What is intergenerational healing?": "ما هو الشفاء بين الأجيال؟",
    "Forcing children to follow the same traditions as their grandparents": "إجبار الأطفال على اتباع نفس تقاليد أجدادهم",
    "Simultaneously parenting your children and giving your inner child what it needed": "تربية أطفالك وإعطاء طفلك الداخلي ما احتاجه في نفس الوقت",
    "Ignoring family history to start completely fresh": "تجاهل تاريخ العائلة للبدء من الصفر",
    "Only healing is possible through professional therapy": "الشفاء ممكن فقط من خلال العلاج المهني",
    "How is a parenting legacy primarily built?": "كيف يُبنى إرث التربية بشكل أساسي؟",
    "Through a few grand, unforgettable moments": "من خلال بضع لحظات كبيرة لا تُنسى",
    "Through expensive experiences and gifts": "من خلال التجارب والهدايا المكلفة",
    "Through thousands of small, daily intentional choices": "من خلال آلاف الخيارات الصغيرة اليومية الواعية",
    "Through reading parenting books": "من خلال قراءة كتب التربية",
    "Is it ever too late to start building an intentional parenting legacy?": "هل فات الأوان لبدء بناء إرث تربوي واعٍ؟",
    "Yes, if your child is past the age of five": "نعم إذا تجاوز طفلك سن الخامسة",
    "Yes, patterns established in early childhood cannot be changed": "نعم الأنماط المُرسّخة في الطفولة المبكرة لا يمكن تغييرها",
    "No, every moment of intentional love adds to the story at any age": "لا كل لحظة حب واعٍ تضيف إلى القصة في أي عمر",
    "It depends on how much damage has already been done": "يعتمد على مقدار الضرر الذي حدث بالفعل",
    "I carry a lot of guilt about mistakes I have already made as a parent. How do I move forward?": "أحمل الكثير من الذنب حول الأخطاء التي ارتكبتها كوالد. كيف أمضي قدماً؟",
    "How can I continue growing as a parent after this program ends?": "كيف أستمر في النمو كوالد بعد انتهاء هذا البرنامج؟",
    "What if my partner is not on the same page about intentional parenting?": "ماذا لو لم يكن شريكي على نفس الصفحة بشأن التربية الواعية؟",
    "Reflect on the parenting legacy you inherited and consciously choose what to keep and transform": "تأمل في إرث التربية الذي ورثته واختر بوعي ما تحتفظ به وما تحوّله",
    "Write a personal parenting legacy statement to guide your daily choices": "اكتب بيان إرث تربوي شخصي لتوجيه خياراتك اليومية",
    "Understand intergenerational healing as a dual process of parenting and reparenting": "افهم الشفاء بين الأجيال كعملية مزدوجة من التربية وإعادة التربية",
    "Adult Attachment Representations, Parental Responsiveness, and Infant Attachment: A Meta-Analysis": "تمثيلات التعلق عند الكبار واستجابة الوالدين وتعلق الرضع: تحليل تلوي",
    "Parenting from the Inside Out: How a Deeper Self-Understanding Can Help You Raise Children Who Thrive": "التربية من الداخل إلى الخارج: كيف يمكن لفهم أعمق للذات أن يساعدك في تربية أطفال مزدهرين",
    "The Legacy Moment": "لحظة الإرث",
    "Legacy Patterns: Keep, Transform, or Release": "أنماط الإرث: احتفظ أو حوّل أو اترك",
    "Match each inherited pattern with the appropriate action.": "طابق كل نمط موروث مع الإجراء المناسب.",
    "Cultural traditions that build identity": "التقاليد الثقافية التي تبني الهوية",
    "Keep: These connect children to something larger": "احتفظ: هذه تربط الأطفال بشيء أكبر",
    "Using shame as discipline": "استخدام الخجل كتأديب",
    "Transform: Replace with accountability-based discipline": "حوّل: استبدل بتأديب قائم على المسؤولية",
    "Family storytelling at gatherings": "رواية القصص العائلية في التجمعات",
    "Keep: Builds shared narrative and belonging": "احتفظ: يبني السردية المشتركة والانتماء",
    'Suppressing emotions ("Big boys don\'t cry")': 'كبت المشاعر ("الأولاد الكبار لا يبكون")',
    "Release: Replaced with emotional freedom for all": "اترك: استُبدل بالحرية العاطفية للجميع",
    "Valuing education and hard work": "تقدير التعليم والعمل الجاد",
    "Keep: These are strengths to carry forward": "احتفظ: هذه نقاط قوة للمضي بها قدماً",
    "Legacy Awareness": "الوعي بالإرث",
    "I am aware of the patterns I inherited from my own upbringing and consciously choose which to keep and which to change.": "أنا واعٍ بالأنماط التي ورثتها من تربيتي وأختار بوعي أيها أحتفظ به وأيها أغيّره.",
    "Operating on Autopilot": "يعمل على الطيار الآلي",
    "Awakening Awareness": "وعي يستيقظ",
    "Intentional Legacy Builder": "بانٍ واعٍ للإرث",
    "The Legacy Triangle": "مثلث الإرث",
    "What You Inherited": "ما ورثته",
    "Patterns, values, and styles from your own upbringing": "أنماط وقيم وأساليب من تربيتك",
    "What You Choose": "ما تختاره",
    "Conscious decisions about what to keep, transform, and release": "قرارات واعية حول ما تحتفظ به وما تحوّله وما تتركه",
    "What You Pass On": "ما تمرره",
    "The values, skills, and emotional patterns your children will carry forward": "القيم والمهارات والأنماط العاطفية التي سيحملها أطفالك للأمام",
}

# Sort by length (longest first) to avoid partial matches
sorted_items = sorted(t.items(), key=lambda x: len(x[0]), reverse=True)

# Process each line
lines = content.split('\n')
new_lines = []

for line in lines:
    if '[Arabic translation needed]' not in line:
        new_lines.append(line)
        continue

    modified = line
    for en_text, ar_text in sorted_items:
        if en_text in modified and '[Arabic translation needed]' in modified:
            modified = modified.replace('[Arabic translation needed]', ar_text, 1)

    new_lines.append(modified)

result = '\n'.join(new_lines)
remaining = result.count('[Arabic translation needed]')
print(f"Remaining after pass 1: {remaining}")

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(result)

print("Pass 1 complete - file saved")
