/* ================================================================
   Invoice Composer — Shared TypeScript Types
   ================================================================
   Used by the rate breakdown, PDF generator, KV store, API routes,
   and admin UI components. Single source of truth for shape.
   ================================================================ */

import type { PricingTierKey, PricingBand } from '@/config/pricing';

export type ComplexityPreset =
  | 'standard'
  | 'plus25'
  | 'plus33'
  | 'plus50'
  | 'custom';

export type PackageKey = 'single' | 'pack3' | 'pack5' | 'pack10';

export type TaxMode = 'manual-hst' | 'none';

export type InvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue' | 'void';

export type PaymentMethodRecord =
  | 'e-transfer'
  | 'wire'
  | 'paypal'
  | 'stripe'
  | 'other'
  | 'unknown';

export interface ClientInput {
  name: string;
  email: string;
  /** ISO-3166-1 alpha-2, uppercase (e.g. 'CA', 'IN', 'AE'). */
  country: string;
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
  };
  phone?: string;
}

export interface InvoiceLineItem {
  /** Local UUID — used as React key. Regenerated each time a row is added. */
  id: string;
  /** Human-readable description of the item (shown on the invoice). */
  description: string;
  /** Quantity — usually 1 (session) but can be fractional hours. */
  quantity: number;
  /** Unit price in the draft's display currency. */
  unitPriceLocal: number;
  /**
   * Optional service slug for reporting categorization. Defaults to the
   * draft's primary `serviceSlug` when not set. Useful for multi-line
   * invoices that bundle several distinct services.
   */
  serviceSlug?: string;
}

export interface InvoiceDraft {
  /** Local UUID — separate from the invoice number assigned at send time. */
  draftId: string;
  client: ClientInput;
  serviceSlug: string;
  complexity: {
    preset: ComplexityPreset;
    percent: number; // 0, 0.25, 0.33, 0.50, or custom (clamped 0..1)
  };
  package: PackageKey;
  /** 0..0.40 downward adjustment for hardship. */
  slidingScalePercent: number;
  /** Optional currency override — if unset, derived from client.country. */
  displayCurrency?: string;
  taxMode: TaxMode;
  allowETransfer: boolean;
  adminNote?: string;
  descriptionOverride?: string;
  daysUntilDue: number;
  /**
   * Manual price override — when enabled, bypasses the auto pricing-engine
   * computation and uses the admin-typed per-session amount instead.
   * The reason field is required for audit transparency.
   */
  manualPrice?: {
    enabled: boolean;
    perSessionLocal: number;
    currency?: string; // optional override for the currency too
    reason?: string;
  };
  /**
   * Optional free-text subject/memo line — shown on the PDF and in the email.
   * Dr. Hala uses this for appointment reminders and per-invoice context.
   * Example: "Appointment reminder: Sunday, April 12 at 2:30pm"
   */
  subject?: string;
  /** When this draft was generated by a recurring schedule, link back. */
  recurringScheduleId?: string;
  /**
   * Optional issue date override as a YYYY-MM-DD string. When set, the
   * invoice is stamped with this date instead of `now`. Also drives the
   * invoice-number YYYYMM prefix (so MHC-202604-HA-3 stays consistent
   * with the issue month). The due date is computed as
   * `issueDate + daysUntilDue` when this is set.
   */
  issueDate?: string;
  /**
   * Optional override for the invoice number. When set, the server uses
   * this string verbatim instead of the auto-generated MHC-YYYYMM-{Init}-{N}
   * format. Does NOT bump the customer's nextInvoiceSeq counter — the next
   * auto-generated invoice for the same customer will use the expected seq.
   */
  invoiceNumberOverride?: string;
  /**
   * Per-invoice override of Settings.customerNotes. When set, the PDF and
   * email show this block instead of the default. Use to tailor specific
   * session notes without changing the global default.
   */
  customerNotesOverride?: string;
  /**
   * Per-invoice override of Settings.termsAndConditions. Array of bullet
   * strings. When set, the PDF T&C section shows these lines instead of
   * the defaults.
   */
  termsOverride?: string[];
  /**
   * Optional multi-line-item list. When populated (length > 0), the rate
   * breakdown sums each item's quantity × unit price and uses that as the
   * subtotal, bypassing the auto pricing-engine. Preserves Dr. Hala's
   * Zoho-era multi-line invoices like "Parenting Session + CC processing fees".
   * When empty or undefined, the single-service behavior applies.
   */
  lineItems?: InvoiceLineItem[];
  /**
   * Optional per-invoice Stripe Payment Link URL. When set, the payment
   * concierge page uses this as the "Pay with Card" destination instead of
   * creating a dynamic Checkout Session. Useful when STRIPE_SECRET_KEY is
   * unavailable (the admin creates a one-time Payment Link in the Stripe
   * dashboard and pastes it here). Empty/undefined → concierge falls back
   * to the generic "customer chooses what to pay" link with an amount hint.
   */
  stripePaymentLink?: string;
  /**
   * Client's preferred email language, copied from the originating Booking
   * (or manually selected by admin when composing standalone). Drives the
   * locale of the invoice + receipt emails. Defaults to 'en' when absent.
   */
  preferredLanguage?: 'en' | 'ar';
  /**
   * ISO timestamp of the linked session's start. When populated, the
   * send-invoice pipeline uses this as the invoice due date (defaulting
   * to "pay by the session") instead of `issueDate + daysUntilDue`.
   * Populated automatically for drafts generated from a Booking; absent
   * for standalone admin invoices (which keep the daysUntilDue fallback).
   */
  sessionStartTime?: string;
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceRateBreakdown {
  tierKey: PricingTierKey;
  serviceSlug: string;
  country: string;
  band: PricingBand;

  /* Base rate (from pricing engine, floor-safe) */
  baseAmountLocal: number;
  baseAmountCAD: number;
  displayCurrency: string;
  floorApplied: boolean;

  /* Complexity step */
  complexityPercent: number;
  afterComplexityLocal: number;
  afterComplexityCAD: number;

  /* Package + sliding scale */
  sessions: number;
  packageDiscountPercent: number;
  slidingScalePercent: number;
  perSessionLocal: number;

  /* Subtotal (pre-tax) */
  subtotalLocal: number;
  subtotalCAD: number;

  /* Tax */
  taxMode: TaxMode;
  taxPercent: number;
  taxAmountLocal: number;
  taxAmountCAD: number;

  /* Grand total */
  totalLocal: number;
  totalCAD: number;

  /* Display helpers */
  formattedBase: string;
  formattedTotal: string;
  formattedTotalCAD: string;
  /** Human-readable one-line formula for transparency. */
  formulaLine: string;
  /** Optional non-blocking warning (e.g., currency auto-corrected). */
  warning?: string;
}

export interface StoredInvoice {
  /** Internal stable ID: inv_{uuid}. */
  invoiceId: string;
  /**
   * Human-readable invoice number. Format: `MHC-YYYYMM-{Initials}-{N}`
   * where `Initials` is derived from the customer name and `N` is the
   * per-customer sequential session counter. Legacy invoices from Phase 2
   * use the older `INV-YYYYMM-NNNN` scheme, and early-2026 invoices used
   * the typo'd `MCH-` prefix — migrated via the migrate-prefix endpoint.
   */
  invoiceNumber: string;
  /** Immutable snapshot of the draft at send time. */
  draft: InvoiceDraft;
  /** Immutable snapshot of the computed breakdown. */
  breakdown: InvoiceRateBreakdown;
  status: InvoiceStatus;
  /** ISO timestamp when the invoice was finalized and sent. */
  issuedAt: string;
  /** ISO timestamp (issuedAt + daysUntilDue). */
  dueDate: string;
  paidAt?: string;
  voidedAt?: string;
  paymentMethod: PaymentMethodRecord;
  createdAt: string;
  updatedAt: string;
  /** Email delivery tracking. */
  emailMessageId?: string;
  emailSentAt?: string;
  /** True if created in Dry Run mode (skips email send). */
  dryRun: boolean;
  /** Dynamic Stripe Checkout URL with the exact invoice amount. */
  stripeCheckoutUrl?: string;
  /**
   * Opaque token used by the payment concierge page to look up this invoice
   * without exposing the invoiceId. Generated at send time via crypto.randomUUID().
   * The email CTA links to `/pay/{paymentToken}` so clients can pay regardless
   * of whether dynamic Stripe sessions are configured.
   */
  paymentToken?: string;
  /**
   * Where this record came from. Defaults to `'native'` when omitted
   * (for backward compat with Phase 2 records).
   * - `native` — created via Compose tab
   * - `zoho-import` — imported from Zoho Books CSV history
   * - `manual-backfill` — inserted programmatically for migration
   */
  origin?: 'native' | 'zoho-import' | 'manual-backfill';
  /**
   * Original invoice number as it appeared in the source system
   * (e.g., Zoho's `MHC-00000746` or `TH-S1`). Searchable from History.
   */
  legacyInvoiceNumber?: string;
  /**
   * Exchange rate snapshot at the time of the original invoice. Used
   * for historical imports so the CAD equivalent reflects the rate
   * at the original issue date, not today's FX.
   */
  legacyExchangeRate?: number;
  /**
   * Preserved original item name from the source system (e.g.,
   * "Parenting Coaching Session"). Used for display fidelity when
   * the canonical `serviceSlug` doesn't match the original wording.
   */
  legacyItemName?: string;
}

export interface InvoiceSettings {
  /* ── Branding ── */
  /** Official business name (e.g. 'Mama Hala Consulting Group'). */
  businessName: string;
  /** Official company registration ID. */
  companyId: string;
  /** Public website URL (no trailing slash). */
  websiteUrl: string;
  /** Booking policy URL — included in T&C section as a clickable link. */
  bookingPolicyUrl: string;
  /** Default Customer Notes block (appears on every invoice). */
  customerNotes: string;
  /** Default Terms & Conditions block — array of bullet points. */
  termsAndConditions: string[];

  /* ── Tax + e-Transfer (Phase 1) ── */
  defaultTaxMode: TaxMode;
  defaultDaysUntilDue: number;
  defaultAllowETransfer: boolean;
  /** Where Canadian clients send Interac e-Transfer. */
  eTransferEmail: string;
  /** Optional wire transfer instructions (shown to non-CA clients). */
  wireInstructions?: string;
  /** Optional PayPal.me link (shown to non-CA clients). */
  paypalLink?: string;
  /**
   * Optional global-default Stripe Payment Link (e.g. a "customer chooses
   * what to pay" link from the Stripe dashboard). Used as the "Pay with
   * Card" destination on the concierge page when:
   *   1. STRIPE_SECRET_KEY is not configured (no dynamic session), AND
   *   2. The invoice draft has no per-invoice stripePaymentLink override.
   *
   * Paste once here and every invoice automatically gets a card button —
   * no more per-invoice pasting. Safe to leave empty (concierge will fall
   * back to e-Transfer / wire / PayPal only).
   */
  defaultStripePaymentLink?: string;
  /** Optional Canadian HST/GST registration number shown on invoice header. */
  hstNumber?: string;
  /** Issuer block shown in the invoice header. */
  issuerBlock: {
    name: string;
    line1: string;
    city: string;
    postalCode: string;
    country: string;
    email: string;
    phone: string;
  };

  /* ── Recurring defaults ── */
  /** When new recurring schedules default to auto-send (vs draft-only). */
  recurringAutoSendDefault: boolean;

  /* ── Dry Run mode ── */
  /** When ON, create invoice + generate PDF + store KV, but skip the email send. */
  dryRun: boolean;
  updatedAt: string;
}

/* ════════════════════════════════════════════════════════════
   Customer Database
   ════════════════════════════════════════════════════════════ */

export interface Customer {
  /** Primary key — lowercase email. */
  email: string;
  name: string;
  /** ISO-2 country code (uppercase). */
  country: string;
  phone?: string;
  /** Optional second phone (distinct from `phone`). Zoho-import populates this from Phone column when MobilePhone is primary. */
  mobilePhone?: string;
  /** Professional salutation (e.g., 'Mrs.', 'Mr.', 'Dr.'). */
  salutation?: string;
  /** Individual or business account type. Default: 'individual'. */
  customerType?: 'individual' | 'business';
  /** For business customers, the company name. For individuals, optional relationship metadata. */
  companyName?: string;
  /** Zoho Books Customer ID — used for cross-referencing imported invoices to imported customers. */
  zohoCustomerId?: string;
  /**
   * 2-4 letter initials used in invoice number generation. Computed from
   * `name` at first-write time and persisted so future invoices for this
   * customer reuse the same prefix. Collision-safe: if two customers share
   * 2-letter initials, both get upgraded to 3-letter.
   * Example: `HA` for "Hala Ali", `HLA` if collision with "Hadia Ahmed".
   */
  effectiveInitials?: string;
  /**
   * Next sequential invoice counter for this customer. Starts at 1 and
   * increments atomically on each new invoice. Feeds into the invoice
   * number: `MHC-YYYYMM-{effectiveInitials}-{nextInvoiceSeq}`.
   */
  nextInvoiceSeq?: number;
  address?: {
    line1?: string;
    line2?: string;
    city?: string;
    state?: string;
    postal_code?: string;
  };
  /** Admin's free-text notes about the client. */
  notes?: string;
  /** Tags for filtering / segmentation. */
  tags?: string[];
  /** Stored display currency from previous invoices. */
  preferredCurrency?: string;
  /** Most-used payment method on past invoices. */
  preferredPaymentMethod?: PaymentMethodRecord;
  /* Aggregated stats — denormalized for fast list rendering */
  totalInvoices: number;
  totalPaidCAD: number;
  outstandingCAD: number;
  firstInvoiceAt?: string;
  lastInvoiceAt?: string;
  /* AI insights cache (refreshed on demand or weekly) */
  aiInsightSummary?: string;
  aiInsightTags?: string[];
  aiInsightUpdatedAt?: string;
  /* Lifecycle */
  createdAt: string;
  updatedAt: string;
  /** Where this record came from. */
  source: 'manual' | 'csv-import' | 'auto-from-invoice';
}

/* ════════════════════════════════════════════════════════════
   Recurring Schedules
   ════════════════════════════════════════════════════════════ */

export type RecurringCadence = 'monthly' | 'weekly';

export interface RecurringSchedule {
  scheduleId: string;
  /** The client this schedule bills. */
  customerEmail: string;
  /** Snapshot of the draft used to spawn each instance. */
  templateDraft: InvoiceDraft;
  /** How often it runs. */
  cadence: RecurringCadence;
  /**
   * For monthly: day-of-month (1-28, capped to avoid Feb edge cases).
   * For weekly: day-of-week (0=Sunday … 6=Saturday).
   */
  anchor: number;
  /** First run (ISO date). */
  startDate: string;
  /** Optional end (ISO date). When passed, schedule auto-deactivates. */
  endDate?: string;
  /** Pause/resume toggle. */
  active: boolean;
  /** When TRUE, generated invoices are sent immediately; when FALSE, left as drafts. */
  autoSend: boolean;
  /**
   * IANA timezone the anchor is interpreted in (e.g. "America/Toronto").
   * Optional for backwards compatibility — legacy schedules without a
   * timezone are treated as UTC, matching the original behaviour. New
   * schedules should always set this so a "fire on the 15th" schedule
   * really fires on the local 15th instead of UTC 00:00 (which can be
   * the previous day in North American timezones).
   */
  timezone?: string;
  /* Telemetry */
  nextRunAt: string;
  lastRunAt?: string;
  totalRuns: number;
  /** All invoice IDs this schedule has spawned. */
  spawnedInvoiceIds: string[];
  /* Lifecycle */
  createdAt: string;
  updatedAt: string;
}

/* ════════════════════════════════════════════════════════════
   Receipt Records
   ════════════════════════════════════════════════════════════ */

export interface ReceiptRecord {
  receiptId: string;
  invoiceId: string;
  invoiceNumber: string;
  /* Snapshot of the payment */
  paidAt: string;
  paymentMethod: PaymentMethodRecord;
  amountPaidLocal: number;
  amountPaidCAD: number;
  currency: string;
  /* Email tracking */
  emailMessageId?: string;
  emailSentAt?: string;
  /** Optional thank-you message (could be AI-personalized in the future). */
  thankYouMessage?: string;
  createdAt: string;
}

/* ── Package config (single source of truth for sessions/discount) ── */

export const PACKAGE_CONFIG: Record<
  PackageKey,
  { sessions: number; discount: number; labelEn: string }
> = {
  single: { sessions: 1, discount: 0, labelEn: 'Single session' },
  pack3: { sessions: 3, discount: 0.05, labelEn: '3-session package' },
  pack5: { sessions: 5, discount: 0.1, labelEn: '5-session package' },
  pack10: { sessions: 10, discount: 0.15, labelEn: '10-session package' },
};

/* ── Complexity presets ── */

export const COMPLEXITY_CONFIG: Record<
  ComplexityPreset,
  { percent: number; labelEn: string }
> = {
  standard: { percent: 0, labelEn: 'Standard' },
  plus25: { percent: 0.25, labelEn: '+25% complexity' },
  plus33: { percent: 0.33, labelEn: '+33% complex (default)' },
  plus50: { percent: 0.5, labelEn: '+50% high complexity' },
  custom: { percent: 0, labelEn: 'Custom %' },
};

/* ════════════════════════════════════════════════════════════
   Zoho Invoice Import — Preview + Result types
   ════════════════════════════════════════════════════════════ */

export type ZohoCustomerMatchMethod =
  | 'zoho-id'
  | 'email'
  | 'name-fuzzy'
  | 'create-new';

export interface ZohoInvoicePreviewCustomer {
  customerName: string;
  zohoCustomerId: string;
  matchedEmail: string | null;
  matchMethod: ZohoCustomerMatchMethod;
  effectiveInitials: string;
  invoiceCount: number;
}

export interface ZohoInvoicePreviewSample {
  legacyNumber: string;
  newNumber: string;
  customerName: string;
  date: string;
  total: string;
  totalCAD: number;
  status: InvoiceStatus;
  origin: 'zoho-import';
}

export interface ZohoInvoiceImportPreview {
  totalRows: number;
  uniqueInvoices: number;
  uniqueCustomers: number;
  existingInvoices: number;
  byStatus: { paid: number; sent: number; overdue: number; void: number };
  byCurrency: Record<string, number>;
  dateRange: { earliest: string; latest: string };
  totalCAD: { paid: number; outstanding: number; void: number };
  warnings: string[];
  customerMatches: ZohoInvoicePreviewCustomer[];
  sample: ZohoInvoicePreviewSample[];
}

export interface ZohoInvoiceImportError {
  row: number;
  legacyNumber: string;
  reason: string;
}

export interface ZohoInvoiceImportResult {
  created: number;
  skipped: number;
  errors: ZohoInvoiceImportError[];
  customersCreated: number;
  customersUpdated: number;
}
